version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install python-pip jq zip python-demjson -y
      - python -m pip install boto boto3 troposphere awacs bcrypt pytz awscli --upgrade
  build:
    commands:
      - python test.py
